export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/baskets'
export const BASKET_PIZZA_ROUTE = '/BasketPizza'
export const ORDER_BOOK = '/orderbook'